[project]
name = "epa-converter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "nuitka>=2.7.16",
    "pandas>=2.3.2",
    "pyqt6>=6.9.1",
    "pyside6>=6.9.2",
    "python-qt>=0.50",
]
